<?php
/**
 * @copyright Copyright (c) PutYourLightsOn
 */

namespace putyourlightson\cacheigniter\models;

use Craft;
use craft\base\Model;
use putyourlightson\cacheigniter\drivers\warmers\GlobalPingWarmer;

/**
 * @property-read array $regionOptions
 */
class SettingsModel extends Model
{
    /**
     * The warmer type to use.
     */
    public string $warmerType = GlobalPingWarmer::class;

    /**
     * The warmer settings.
     */
    public array $warmerSettings = [];

    /**
     * The warmer type classes to add to the plugin’s default warmer types.
     *
     * @var string[]
     */
    public array $warmerTypes = [];

    /**
     * URLs that should appear in the utility by default.
     *
     * @var array<int, array<int, string>>
     */
    public array $utilityUrls = [];

    /**
     * The number of seconds to wait before warming refreshed site URIs.
     */
    public int $refreshDelay = 30;

    /**
     * Site URI patterns to include in warming whenever they are refreshed or generated by Blitz. Set `siteId` to a blank string to indicate all sites.
     *
     * @var array<int, array{
     *          siteId: ?int,
     *          uriPattern: string,
     *      }>
     */
    public array $includedRefreshUriPatterns = [];

    /**
     * Site URI patterns to exclude from warming whenever they are refreshed or generated by Blitz(overrides any matching patterns to include). Set `siteId` to a blank string to indicate all sites.
     *
     * @var array<int, array{
     *          siteId: ?int,
     *          uriPattern: string,
     *      }>
     */
    public array $excludedRefreshUriPatterns = [];

    /**
     * The priority to give the warm job (the lower the number, the higher the priority).
     */
    public int $warmJobPriority = 101;

    /**
     * The maximum length of URLs that may be warmed. Increasing this value requires manually updating the limit in the `url` column of the `cacheigniter_urls` database table. Note that the prefix length limit is 3072 bytes for InnoDB tables that use the DYNAMIC or COMPRESSED row format. Assuming a `utf8mb4` character set and a maximum of 4 bytes for each character, this is 768 characters.
     * https://dev.mysql.com/doc/refman/8.0/en/column-indexes.html#column-indexes-prefix
     */
    public int $maxUrlLength = 500;

    /**
     * @inheritdoc
     */
    public function attributeLabels(): array
    {
        $labels = parent::attributeLabels();
        $labels['refreshSiteUris'] = Craft::t('cache-igniter', 'Refresh Site URIs');
        $labels['utilityUrls'] = Craft::t('cache-igniter', 'Utility URLs');

        return $labels;
    }
}
