<?php
/**
 * @copyright Copyright (c) PutYourLightsOn
 */

/**
 * Cache Igniter config.php
 *
 * This file exists only as a template for the Cache Igniter settings.
 * It does nothing on its own.
 *
 * Don't edit this file, instead copy it to 'craft/config' as 'cache-igniter.php'
 * and make your changes there to override default settings.
 *
 * Once copied to 'craft/config', this file will be multi-environment aware as
 * well, so you can have different settings groups for each environment, just as
 * you do for 'general.php'
 */

return [
    '*' => [
        // The warmer type to use.
        //'warmerType' => 'putyourlightson\cacheigniter\drivers\warmers\GlobalPingWarmer',

        // The warmer settings.
        //'warmerSettings' => [
        //    'locations' => [
        //        'US West',
        //        'US East',
        //        'Brazil',
        //        'Germany',
        //        'Australia',
        //    ],
        //],

        // The warmer type classes to add to the plugin’s default warmer types.
        //'warmerTypes' => [],

        // URLs that should appear in the utility by default.
        //'utilityUrls' => [],

        //The number of seconds to wait before warming refreshed site URIs.
        //'refreshDelay' => 30,

        // Site URI patterns to include in warming whenever they are refreshed or generated by Blitz. Set `siteId` to a blank string to indicate all sites.
        //'includedRefreshUriPatterns' => [
        //    [
        //        'siteId' => 1,
        //        'uriPattern' => '',
        //    ],
        //    [
        //        'siteId' => 2,
        //        'uriPattern' => 'articles/.*',
        //    ],
        //],

        // Site URI patterns to exclude from warming whenever they are refreshed or generated by Blitz(overrides any matching patterns to include). Set `siteId` to a blank string to indicate all sites.
        //'excludedRefreshUriPatterns' => [
        //    [
        //        'siteId' => '',
        //        'uriPattern' => 'dynamic',
        //    ],
        //],

        // The priority to give the warm job (the lower the number, the higher the priority).
        //'warmJobPriority' => 101,
    ],
];
