<?php
/**
 * @copyright Copyright (c) PutYourLightsOn
 */

/**
 * Cache Igniter config.php
 *
 * This file exists only as a template for the Cache Igniter settings.
 * It does nothing on its own.
 *
 * Don't edit this file, instead copy it to 'craft/config' as 'cache-igniter.php'
 * and make your changes there to override default settings.
 *
 * Once copied to 'craft/config', this file will be multi-environment aware as
 * well, so you can have different settings groups for each environment, just as
 * you do for 'general.php'
 */

return [
    '*' => [
        // A SpeedVitals API key.
        //'speedVitalsApiKey' => '',

        // Regions to warm.
        //'regions' => [
        //    'america',
        //    'asia',
        //    'europe',
        //],

        // The percent of the time at which to warm URLS whenever they are refreshed or generated by Blitz (0 = never, 50 = half of the time, 100 = always).
        //'refreshRate' => 100,

        // URLs to warm whenever they are refreshed or generated by Blitz.
        //'refreshUrls' => [],

        // URLs that should appear in the utility by default
        //'utilityUrls' => [],
    ],
];
